-- ============================================================================
--  schema.sql — Postgres (Neon) schema, converted from the live MySQL DB.
--  Source of truth was `SHOW CREATE TABLE` against the running MySQL instance
--  (the original schema was never checked into this repo — only
--  relateme_extras.sql, which documents incremental changes on top of it).
--
--  Conversion rules applied:
--    - AUTO_INCREMENT          -> GENERATED BY DEFAULT AS IDENTITY (not ALWAYS,
--                                 so the data-load script can insert explicit
--                                 PK values copied from MySQL, then the
--                                 sequence is reset to MAX(id)+1 afterward)
--    - ENUM(...)                -> TEXT + CHECK (col IN (...))
--    - DATETIME                 -> TIMESTAMP
--    - YEAR                     -> SMALLINT
--    - JSON                     -> JSONB
--    - TINYINT(1) flag columns  -> SMALLINT (kept as 0/1, not BOOLEAN — the
--                                 app already reads/writes these as JS 1/0)
--    - ENGINE/CHARSET/COLLATE/COMMENT table+column options -> dropped
--    - ON UPDATE CURRENT_TIMESTAMP -> handled by a shared trigger (Section 4)
--
--  Layout: tables (no FKs) -> indexes -> foreign keys -> updated_at triggers.
--  Splitting FKs into their own ALTER TABLE section avoids having to
--  hand-order 26 tables around 70 cross-references.
-- ============================================================================

-- ============================================================================
-- SECTION 1 — TABLES
-- ============================================================================

CREATE TABLE tbl_app_user (
  user_id         CHAR(36)     NOT NULL PRIMARY KEY,
  email           VARCHAR(255) NOT NULL UNIQUE,
  full_name       VARCHAR(200) NOT NULL,
  user_role       TEXT         NOT NULL CHECK (user_role IN ('Admin','Candidate','Volunteer')),
  approval_status TEXT         NOT NULL DEFAULT 'Pending' CHECK (approval_status IN ('Pending','Active','Deactivated')),
  created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by      CHAR(36),
  updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by      CHAR(36)
);

CREATE TABLE tbl_org_details (
  org_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_name      VARCHAR(300) NOT NULL,
  org_reg_no    VARCHAR(100) UNIQUE,
  org_type      TEXT         NOT NULL CHECK (org_type IN ('CA','NON_CA')),
  org_structure TEXT         CHECK (org_structure IN ('PARTNERSHIP','SOLE_PROP','LLP','PRIVATE_LTD')),
  org_status    TEXT         NOT NULL DEFAULT 'ACTIVE' CHECK (org_status IN ('ACTIVE','INACTIVE')),
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by    CHAR(36),
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by    CHAR(36),
  member_count  INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE tbl_institute_details (
  institute_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institute_name   VARCHAR(300) NOT NULL,
  institute_type   TEXT         NOT NULL CHECK (institute_type IN ('SCHOOL','COLLEGE','UNIVERSITY','INSTITUTE')),
  affiliation_type TEXT         CHECK (affiliation_type IN ('AFFILIATED','AUTONOMOUS','DEEMED')),
  governing_body   VARCHAR(150),
  established_year SMALLINT,
  institute_status TEXT         NOT NULL DEFAULT 'ACTIVE' CHECK (institute_status IN ('ACTIVE','INACTIVE')),
  created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by       CHAR(36),
  updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by       CHAR(36)
);

CREATE TABLE tbl_ca_member (
  icai_membership_no  VARCHAR(20)   NOT NULL PRIMARY KEY,
  member_first_name   VARCHAR(400),
  member_middle_name  VARCHAR(400),
  member_last_name    VARCHAR(400),
  member_display_name VARCHAR(1200) NOT NULL,
  member_dob           DATE,
  member_gender        TEXT      CHECK (member_gender IN ('M','F','O')),
  member_status        TEXT      NOT NULL DEFAULT 'Active' CHECK (member_status IN ('Active','Inactive')),
  member_region_base   VARCHAR(100),
  member_deceased_date DATE,
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by           CHAR(36),
  updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by           CHAR(36)
);

CREATE TABLE tbl_ca_member_fact (
  icai_membership_no    VARCHAR(20) NOT NULL PRIMARY KEY,
  is_fca_member         TEXT        NOT NULL CHECK (is_fca_member IN ('Y','N')),
  membership_grade      TEXT        NOT NULL CHECK (membership_grade IN ('ACA','FCA')),
  cop_status             TEXT      CHECK (cop_status IN ('NOT HOLDING','FULL TIME','PART TIME')),
  member_photo_url       VARCHAR(500),
  member_visiting_url    VARCHAR(500),
  associate_year         VARCHAR(10),
  member_enrollment_date DATE,
  fellow_year            VARCHAR(10),
  member_fca_date        DATE,
  created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by             CHAR(36),
  updated_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by             CHAR(36)
);

CREATE TABLE tbl_user_auth (
  user_id                 CHAR(36)     NOT NULL PRIMARY KEY,
  password_hash           VARCHAR(255) NOT NULL,
  created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  first_login_at          TIMESTAMP,
  onboarding_completed_at TIMESTAMP
);

CREATE TABLE tbl_user_universe (
  user_id            CHAR(36)    NOT NULL,
  icai_membership_no VARCHAR(20) NOT NULL,
  added_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, icai_membership_no)
);

CREATE TABLE tbl_campaign_goal (
  goal_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  election_year SMALLINT NOT NULL,
  prev_quota   INTEGER   NOT NULL DEFAULT 0,
  target_total INTEGER   NOT NULL DEFAULT 0,
  target_p1    INTEGER   NOT NULL DEFAULT 0,
  target_p2    INTEGER   NOT NULL DEFAULT 0,
  target_p3    INTEGER   NOT NULL DEFAULT 0,
  target_p4    INTEGER   NOT NULL DEFAULT 0,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by   CHAR(36)
);

CREATE TABLE tbl_candidate_onboarding_profile (
  user_id                   CHAR(36)  NOT NULL PRIMARY KEY,
  seeking_vote_cities       JSONB,
  icai_branch               VARCHAR(150),
  practice_cities           JSONB,
  past_firm_org_ids         JSONB,
  is_articleship_principal  TEXT      CHECK (is_articleship_principal IN ('Y','N')),
  articleship_student_count INTEGER,
  coaching_institutes       JSONB,
  ca_final_year             SMALLINT,
  graduation_college        VARCHAR(200),
  outreach_start_date       DATE,
  created_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tbl_dnd (
  dnd_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no VARCHAR(20) NOT NULL UNIQUE,
  dnd_from           DATE        NOT NULL,
  reason             VARCHAR(500),
  dnd_status         TEXT        NOT NULL DEFAULT 'Active' CHECK (dnd_status IN ('Active','Removed')),
  removed_at         TIMESTAMP,
  removed_by         CHAR(36),
  created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         CHAR(36)
);

CREATE TABLE tbl_member_action_tag (
  tag_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no VARCHAR(20) NOT NULL,
  tag_type           TEXT        NOT NULL CHECK (tag_type IN ('call_list','meet_list','competitor')),
  created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  UNIQUE (icai_membership_no, tag_type)
);

CREATE TABLE tbl_member_education (
  member_education_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no   VARCHAR(20) NOT NULL,
  qualification        VARCHAR(20),
  specialisation       VARCHAR(100),
  qualification_family VARCHAR(100),
  study_mode           TEXT      CHECK (study_mode IN ('Correspondence','Regular','Distance')),
  institution_name     VARCHAR(100),
  university_name      VARCHAR(100),
  graduation_year      SMALLINT,
  batch_year_from      SMALLINT,
  batch_year_to        SMALLINT,
  education_status     TEXT      CHECK (education_status IN ('Valid','Invalid')),
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by           CHAR(36),
  updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by           CHAR(36)
);

CREATE TABLE tbl_member_emails (
  email_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no VARCHAR(20)  NOT NULL,
  email_address      VARCHAR(400) NOT NULL,
  email_type         TEXT         NOT NULL CHECK (email_type IN ('Personal','Company')),
  email_status       TEXT         NOT NULL DEFAULT 'Active' CHECK (email_status IN ('Active','Inactive')),
  email_is_primary   SMALLINT     NOT NULL DEFAULT 0,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         CHAR(36)
);

CREATE TABLE tbl_member_label (
  label_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no VARCHAR(20)  NOT NULL,
  label_text         VARCHAR(100) NOT NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36)
);

CREATE TABLE tbl_member_phones (
  phone_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no VARCHAR(20) NOT NULL,
  phone_country_code VARCHAR(8)  NOT NULL,
  phone_number       VARCHAR(20) NOT NULL,
  phone_number_full  VARCHAR(30) NOT NULL,
  phone_type         TEXT        NOT NULL CHECK (phone_type IN ('Personal','Official')),
  is_whatsapp        SMALLINT    NOT NULL DEFAULT 0,
  phone_status       TEXT        NOT NULL DEFAULT 'Active' CHECK (phone_status IN ('Active','Inactive')),
  phone_is_primary   SMALLINT    NOT NULL DEFAULT 0,
  created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         CHAR(36)
);

CREATE TABLE tbl_member_social_profiles (
  social_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no VARCHAR(20) NOT NULL,
  social_platform    TEXT      CHECK (social_platform IN ('Facebook','LinkedIn','Instagram','Twitter')),
  social_handle_url  VARCHAR(255),
  social_media_type  TEXT      CHECK (social_media_type IN ('Personal','Official','Generic')),
  social_status      TEXT      NOT NULL DEFAULT 'Active' CHECK (social_status IN ('Active','Inactive')),
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         CHAR(36),
  UNIQUE (icai_membership_no, social_platform)
);

CREATE TABLE tbl_voter (
  voter_record_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  election_year      SMALLINT    NOT NULL,
  voter_id           VARCHAR(50) NOT NULL,
  icai_membership_no VARCHAR(20) NOT NULL,
  voter_booth_no     VARCHAR(50),
  voter_type         TEXT        NOT NULL CHECK (voter_type IN ('Booth','Postal')),
  voter_sub_type     TEXT        CHECK (voter_sub_type IN ('Booth-Region','Booth-Other Region','Postal-Domestic','Postal-Foreign')),
  voter_status       TEXT        NOT NULL DEFAULT 'Active' CHECK (voter_status IN ('Active','Inactive','Blocked')),
  created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         CHAR(36),
  UNIQUE (election_year, voter_id)
);

CREATE TABLE tbl_voter_education_history (
  edu_hist_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no           VARCHAR(20) NOT NULL,
  edu_course_type              TEXT        NOT NULL CHECK (edu_course_type IN ('CA Course','Articleship','University','Coaching','Other')),
  institute_id                 BIGINT,
  org_id                       BIGINT,
  qualification_name           VARCHAR(200),
  from_year                    SMALLINT,
  to_year                      SMALLINT,
  edu_status                   TEXT        NOT NULL CHECK (edu_status IN ('Active','Completed','Unknown')),
  created_at                   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by                   CHAR(36),
  updated_at                   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by                   CHAR(36),
  principal_icai_membership_no VARCHAR(20)
);

CREATE TABLE tbl_voter_icai_roles (
  role_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no VARCHAR(20)  NOT NULL,
  role_type          TEXT         NOT NULL CHECK (role_type IN ('Branch Committee','CPE Speaker','ICAI Committee','Specialization','Other')),
  role_value         VARCHAR(300) NOT NULL,
  from_year          SMALLINT,
  to_year            SMALLINT,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         CHAR(36)
);

CREATE TABLE tbl_voter_preference (
  pref_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no  VARCHAR(20) NOT NULL UNIQUE,
  preference_tier     TEXT        NOT NULL CHECK (preference_tier IN ('p1','p2','p3','p4','un')),
  support_status      TEXT        NOT NULL CHECK (support_status IN ('Confirmed','Lean','Undecided','Opposition','Unknown')),
  pvs_score           INTEGER,
  pvs_score_previous  INTEGER,
  created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by          CHAR(36),
  updated_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by          CHAR(36)
);

CREATE TABLE tbl_voter_voting_history (
  vh_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no VARCHAR(20) NOT NULL,
  election_year      SMALLINT    NOT NULL,
  voter_id           VARCHAR(50),
  voter_booth_no     VARCHAR(50),
  voter_type         TEXT      CHECK (voter_type IN ('Booth','Postal')),
  voter_sub_type     TEXT      CHECK (voter_sub_type IN ('Booth-Region','Booth-Other Region','Postal-Domestic','Postal-Foreign')),
  voter_status       TEXT      NOT NULL DEFAULT 'Active' CHECK (voter_status IN ('Active','Inactive','Blocked')),
  voted              TEXT      NOT NULL DEFAULT 'N' CHECK (voted IN ('Y','N')),
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         CHAR(36),
  UNIQUE (icai_membership_no, election_year)
);

CREATE TABLE tbl_work_history (
  wh_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icai_membership_no VARCHAR(20)  NOT NULL,
  org_id             BIGINT       NOT NULL,
  org_reg_no         VARCHAR(100),
  designation        VARCHAR(100) NOT NULL,
  from_year          SMALLINT,
  to_year            SMALLINT,
  work_type          TEXT         NOT NULL CHECK (work_type IN ('Employment','Articleship','Practice')),
  work_status        TEXT         NOT NULL DEFAULT 'Active' CHECK (work_status IN ('Active','Inactive','Not a member','Expired')),
  remark             VARCHAR(500),
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         CHAR(36)
);

CREATE TABLE tbl_activity (
  activity_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_type       TEXT      NOT NULL CHECK (activity_type IN ('Call','Meeting','WhatsApp','SMS','Email','Event','Referral')),
  activity_date       DATE      NOT NULL,
  description         TEXT,
  followup_date       DATE,
  followup_note       TEXT,
  assigned_to         CHAR(36),
  preference_outcome  TEXT      CHECK (preference_outcome IN ('Confirmed','Lean','Undecided','Opposition','Unknown')),
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by          CHAR(36),
  updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by          CHAR(36)
);

CREATE TABLE tbl_activity_participant (
  ap_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id        BIGINT      NOT NULL,
  icai_membership_no VARCHAR(20) NOT NULL,
  participant_role   TEXT        NOT NULL CHECK (participant_role IN ('Primary','Secondary')),
  created_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by         CHAR(36),
  updated_at         TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         CHAR(36),
  UNIQUE (activity_id, icai_membership_no)
);

CREATE TABLE tbl_booth_address_master (
  booth_address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booth_state      VARCHAR(100) NOT NULL,
  booth_state_code VARCHAR(10),
  booth_name       VARCHAR(200) NOT NULL,
  booth_city       VARCHAR(100) NOT NULL,
  booth_address    VARCHAR(500),
  booth_pincode    VARCHAR(20),
  booth_url        VARCHAR(500),
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by       CHAR(36),
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by       CHAR(36)
);

CREATE TABLE tbl_booth_master (
  booth_master_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  election_year    SMALLINT    NOT NULL,
  boothno          VARCHAR(50) NOT NULL,
  boothno_old      VARCHAR(50),
  booth_address_id BIGINT,
  created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by       CHAR(36),
  updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by       CHAR(36),
  UNIQUE (election_year, boothno)
);

-- ============================================================================
-- SECTION 2 — INDEXES (mirrors every non-unique `KEY` from the MySQL schema)
-- ============================================================================

CREATE INDEX idx_activity_date            ON tbl_activity (activity_date);
CREATE INDEX idx_activity_type            ON tbl_activity (activity_type);
CREATE INDEX fk_activity_assigned_to      ON tbl_activity (assigned_to);
CREATE INDEX fk_activity_created_by       ON tbl_activity (created_by);
CREATE INDEX fk_activity_updated_by       ON tbl_activity (updated_by);

CREATE INDEX fk_ap_created_by             ON tbl_activity_participant (created_by);
CREATE INDEX fk_ap_updated_by             ON tbl_activity_participant (updated_by);
CREATE INDEX fk_ap_member                 ON tbl_activity_participant (icai_membership_no);

CREATE INDEX fk_app_user_created_by       ON tbl_app_user (created_by);
CREATE INDEX fk_app_user_updated_by       ON tbl_app_user (updated_by);

CREATE INDEX idx_booth_addr_city          ON tbl_booth_address_master (booth_city);
CREATE INDEX fk_booth_addr_created_by     ON tbl_booth_address_master (created_by);
CREATE INDEX fk_booth_addr_updated_by     ON tbl_booth_address_master (updated_by);

CREATE INDEX idx_booth_master_addr        ON tbl_booth_master (booth_address_id);
CREATE INDEX fk_booth_master_created_by   ON tbl_booth_master (created_by);
CREATE INDEX fk_booth_master_updated_by   ON tbl_booth_master (updated_by);

CREATE INDEX idx_ca_member_region         ON tbl_ca_member (member_region_base);
CREATE INDEX idx_ca_member_status         ON tbl_ca_member (member_status);
CREATE INDEX fk_ca_member_created_by      ON tbl_ca_member (created_by);
CREATE INDEX fk_ca_member_updated_by      ON tbl_ca_member (updated_by);

CREATE INDEX fk_member_fact_created_by    ON tbl_ca_member_fact (created_by);
CREATE INDEX fk_member_fact_updated_by    ON tbl_ca_member_fact (updated_by);

CREATE INDEX idx_goal_year                ON tbl_campaign_goal (election_year);
CREATE INDEX idx_goal_created             ON tbl_campaign_goal (created_at);
CREATE INDEX fk_goal_created_by           ON tbl_campaign_goal (created_by);

CREATE INDEX fk_dnd_created_by            ON tbl_dnd (created_by);
CREATE INDEX fk_dnd_removed_by            ON tbl_dnd (removed_by);
CREATE INDEX fk_dnd_updated_by            ON tbl_dnd (updated_by);

CREATE INDEX fk_institute_created_by      ON tbl_institute_details (created_by);
CREATE INDEX fk_institute_updated_by      ON tbl_institute_details (updated_by);

CREATE INDEX idx_tag_type                 ON tbl_member_action_tag (tag_type);
CREATE INDEX fk_member_tag_created_by     ON tbl_member_action_tag (created_by);

CREATE INDEX idx_member_education_member  ON tbl_member_education (icai_membership_no);
CREATE INDEX fk_member_education_created_by ON tbl_member_education (created_by);
CREATE INDEX fk_member_education_updated_by ON tbl_member_education (updated_by);

CREATE INDEX idx_member_emails_member     ON tbl_member_emails (icai_membership_no);
CREATE INDEX fk_member_emails_created_by  ON tbl_member_emails (created_by);
CREATE INDEX fk_member_emails_updated_by  ON tbl_member_emails (updated_by);

CREATE INDEX idx_label_member             ON tbl_member_label (icai_membership_no);
CREATE INDEX fk_member_label_created_by   ON tbl_member_label (created_by);

CREATE INDEX idx_member_phones_member     ON tbl_member_phones (icai_membership_no);
CREATE INDEX fk_member_phones_created_by  ON tbl_member_phones (created_by);
CREATE INDEX fk_member_phones_updated_by  ON tbl_member_phones (updated_by);

CREATE INDEX fk_social_created_by         ON tbl_member_social_profiles (created_by);
CREATE INDEX fk_social_updated_by         ON tbl_member_social_profiles (updated_by);

CREATE INDEX idx_org_type                 ON tbl_org_details (org_type);
CREATE INDEX fk_org_created_by            ON tbl_org_details (created_by);
CREATE INDEX fk_org_updated_by            ON tbl_org_details (updated_by);
CREATE INDEX idx_org_member_count         ON tbl_org_details (member_count);

CREATE INDEX idx_uu_member                ON tbl_user_universe (icai_membership_no);

CREATE INDEX idx_voter_member             ON tbl_voter (icai_membership_no);
CREATE INDEX idx_voter_type               ON tbl_voter (voter_type);
CREATE INDEX fk_voter_created_by          ON tbl_voter (created_by);
CREATE INDEX fk_voter_updated_by          ON tbl_voter (updated_by);

CREATE INDEX idx_edu_institute            ON tbl_voter_education_history (institute_id);
CREATE INDEX idx_edu_org                  ON tbl_voter_education_history (org_id);
CREATE INDEX fk_edu_created_by            ON tbl_voter_education_history (created_by);
CREATE INDEX fk_edu_updated_by            ON tbl_voter_education_history (updated_by);
CREATE INDEX idx_edu_member               ON tbl_voter_education_history (icai_membership_no);
CREATE INDEX idx_edu_principal2           ON tbl_voter_education_history (principal_icai_membership_no);

CREATE INDEX idx_roles_type               ON tbl_voter_icai_roles (role_type);
CREATE INDEX fk_roles_created_by          ON tbl_voter_icai_roles (created_by);
CREATE INDEX fk_roles_updated_by          ON tbl_voter_icai_roles (updated_by);
CREATE INDEX idx_roles_member             ON tbl_voter_icai_roles (icai_membership_no);

CREATE INDEX idx_pref_tier                ON tbl_voter_preference (preference_tier);
CREATE INDEX idx_pref_support             ON tbl_voter_preference (support_status);
CREATE INDEX fk_pref_created_by           ON tbl_voter_preference (created_by);
CREATE INDEX fk_pref_updated_by           ON tbl_voter_preference (updated_by);

CREATE INDEX fk_vh_created_by             ON tbl_voter_voting_history (created_by);
CREATE INDEX fk_vh_updated_by             ON tbl_voter_voting_history (updated_by);
CREATE INDEX idx_vvh_booth                ON tbl_voter_voting_history (voter_booth_no);

CREATE INDEX idx_work_org                 ON tbl_work_history (org_id);
CREATE INDEX fk_work_created_by           ON tbl_work_history (created_by);
CREATE INDEX fk_work_updated_by           ON tbl_work_history (updated_by);
CREATE INDEX idx_work_member              ON tbl_work_history (icai_membership_no);

-- ============================================================================
-- SECTION 3 — FOREIGN KEYS
-- ============================================================================

ALTER TABLE tbl_app_user ADD CONSTRAINT fk_app_user_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_app_user ADD CONSTRAINT fk_app_user_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_org_details ADD CONSTRAINT fk_org_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_org_details ADD CONSTRAINT fk_org_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_institute_details ADD CONSTRAINT fk_institute_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_institute_details ADD CONSTRAINT fk_institute_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_ca_member ADD CONSTRAINT fk_ca_member_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_ca_member ADD CONSTRAINT fk_ca_member_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_ca_member_fact ADD CONSTRAINT fk_member_fact_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_ca_member_fact ADD CONSTRAINT fk_member_fact_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_ca_member_fact ADD CONSTRAINT fk_member_fact_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_user_auth ADD CONSTRAINT fk_user_auth_user FOREIGN KEY (user_id) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE;

ALTER TABLE tbl_user_universe ADD CONSTRAINT fk_uu_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_user_universe ADD CONSTRAINT fk_uu_user FOREIGN KEY (user_id) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_campaign_goal ADD CONSTRAINT fk_goal_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_candidate_onboarding_profile ADD CONSTRAINT fk_onboarding_profile_user FOREIGN KEY (user_id) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE;

ALTER TABLE tbl_dnd ADD CONSTRAINT fk_dnd_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_dnd ADD CONSTRAINT fk_dnd_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_dnd ADD CONSTRAINT fk_dnd_removed_by FOREIGN KEY (removed_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_dnd ADD CONSTRAINT fk_dnd_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_member_action_tag ADD CONSTRAINT fk_member_tag_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE tbl_member_action_tag ADD CONSTRAINT fk_member_tag_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_member_education ADD CONSTRAINT fk_member_education_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_member_education ADD CONSTRAINT fk_member_education_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_member_education ADD CONSTRAINT fk_member_education_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_member_emails ADD CONSTRAINT fk_member_emails_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_member_emails ADD CONSTRAINT fk_member_emails_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_member_emails ADD CONSTRAINT fk_member_emails_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_member_label ADD CONSTRAINT fk_member_label_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE tbl_member_label ADD CONSTRAINT fk_member_label_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_member_phones ADD CONSTRAINT fk_member_phones_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_member_phones ADD CONSTRAINT fk_member_phones_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_member_phones ADD CONSTRAINT fk_member_phones_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_member_social_profiles ADD CONSTRAINT fk_social_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_member_social_profiles ADD CONSTRAINT fk_social_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_member_social_profiles ADD CONSTRAINT fk_social_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_voter ADD CONSTRAINT fk_voter_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter ADD CONSTRAINT fk_voter_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter ADD CONSTRAINT fk_voter_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_voter_education_history ADD CONSTRAINT fk_edu_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter_education_history ADD CONSTRAINT fk_edu_institute FOREIGN KEY (institute_id) REFERENCES tbl_institute_details (institute_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter_education_history ADD CONSTRAINT fk_edu_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter_education_history ADD CONSTRAINT fk_edu_org FOREIGN KEY (org_id) REFERENCES tbl_org_details (org_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter_education_history ADD CONSTRAINT fk_edu_principal2 FOREIGN KEY (principal_icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE tbl_voter_education_history ADD CONSTRAINT fk_edu_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_voter_icai_roles ADD CONSTRAINT fk_roles_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter_icai_roles ADD CONSTRAINT fk_roles_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter_icai_roles ADD CONSTRAINT fk_roles_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_voter_preference ADD CONSTRAINT fk_pref_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter_preference ADD CONSTRAINT fk_pref_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter_preference ADD CONSTRAINT fk_pref_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_voter_voting_history ADD CONSTRAINT fk_vh_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE tbl_voter_voting_history ADD CONSTRAINT fk_vh_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_voter_voting_history ADD CONSTRAINT fk_vh_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE tbl_work_history ADD CONSTRAINT fk_work_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_work_history ADD CONSTRAINT fk_work_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_work_history ADD CONSTRAINT fk_work_org FOREIGN KEY (org_id) REFERENCES tbl_org_details (org_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_work_history ADD CONSTRAINT fk_work_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_activity ADD CONSTRAINT fk_activity_assigned_to FOREIGN KEY (assigned_to) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_activity ADD CONSTRAINT fk_activity_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_activity ADD CONSTRAINT fk_activity_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_activity_participant ADD CONSTRAINT fk_ap_activity FOREIGN KEY (activity_id) REFERENCES tbl_activity (activity_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_activity_participant ADD CONSTRAINT fk_ap_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_activity_participant ADD CONSTRAINT fk_ap_member FOREIGN KEY (icai_membership_no) REFERENCES tbl_ca_member (icai_membership_no) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tbl_activity_participant ADD CONSTRAINT fk_ap_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tbl_booth_address_master ADD CONSTRAINT fk_booth_addr_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE tbl_booth_address_master ADD CONSTRAINT fk_booth_addr_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE tbl_booth_master ADD CONSTRAINT fk_booth_master_addr FOREIGN KEY (booth_address_id) REFERENCES tbl_booth_address_master (booth_address_id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE tbl_booth_master ADD CONSTRAINT fk_booth_master_created_by FOREIGN KEY (created_by) REFERENCES tbl_app_user (user_id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE tbl_booth_master ADD CONSTRAINT fk_booth_master_updated_by FOREIGN KEY (updated_by) REFERENCES tbl_app_user (user_id) ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================================
-- SECTION 4 — updated_at TRIGGERS (replaces MySQL's ON UPDATE CURRENT_TIMESTAMP)
--  21 of the 26 tables have it; tbl_ca_member_fact, tbl_campaign_goal,
--  tbl_user_universe, tbl_app_user(*) -- wait, app_user IS in the list, see below.
--  Applied to exactly the tables confirmed (via information_schema) to have
--  ON UPDATE CURRENT_TIMESTAMP on updated_at in the live MySQL schema.
-- ============================================================================

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_upd_tbl_activity                      BEFORE UPDATE ON tbl_activity                      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_activity_participant           BEFORE UPDATE ON tbl_activity_participant           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_app_user                       BEFORE UPDATE ON tbl_app_user                       FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_booth_address_master           BEFORE UPDATE ON tbl_booth_address_master           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_booth_master                   BEFORE UPDATE ON tbl_booth_master                   FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_ca_member                      BEFORE UPDATE ON tbl_ca_member                      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_candidate_onboarding_profile   BEFORE UPDATE ON tbl_candidate_onboarding_profile   FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_dnd                            BEFORE UPDATE ON tbl_dnd                            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_institute_details              BEFORE UPDATE ON tbl_institute_details              FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_member_education               BEFORE UPDATE ON tbl_member_education               FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_member_emails                  BEFORE UPDATE ON tbl_member_emails                  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_member_phones                  BEFORE UPDATE ON tbl_member_phones                  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_member_social_profiles         BEFORE UPDATE ON tbl_member_social_profiles         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_org_details                    BEFORE UPDATE ON tbl_org_details                    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_user_auth                      BEFORE UPDATE ON tbl_user_auth                      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_voter                          BEFORE UPDATE ON tbl_voter                          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_voter_education_history        BEFORE UPDATE ON tbl_voter_education_history        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_voter_icai_roles               BEFORE UPDATE ON tbl_voter_icai_roles               FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_voter_preference               BEFORE UPDATE ON tbl_voter_preference               FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_voter_voting_history           BEFORE UPDATE ON tbl_voter_voting_history           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_upd_tbl_work_history                   BEFORE UPDATE ON tbl_work_history                   FOR EACH ROW EXECUTE FUNCTION set_updated_at();
